In [1]:
import nltk

In [6]:
from nltk.corpus import brown

In [9]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [11]:
print(brown.categories())
len(brown.categories())

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


15

In [12]:
data = brown.sents(categories='adventure')

In [15]:
print(data[0])

['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.']


In [17]:
' '.join(data[0])

'Dan Morgan told himself he would forget Ann Turner .'

In [18]:
data = brown.sents?

In [19]:
data = brown.sents(categories='romance')

In [22]:
' '.join(data[2])

'The Old Man was unimportant .'

# Tokenization and StopWords

In [26]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [27]:
from nltk.tokenize import word_tokenize

In [45]:
#multiline sentence in 3 atastrophe
document = """She is a bad girl. It's raining outside. 
She must have inside the house."""

sentence = "I love her she is nice to me , by @girishchhonkar.com."


In [32]:
sents=sent_tokenize(document)

In [34]:
print(sents)

['She is a bad girl.', "It's raining outside.", 'She must have inside the house.']


In [36]:
sents[1]

"It's raining outside."

In [46]:
sentence.split()

['I',
 'love',
 'her',
 'she',
 'is',
 'nice',
 'to',
 'me',
 ',',
 'by',
 '@girishchhonkar.com.']

In [47]:
words = word_tokenize(sentence)

In [48]:
words

['I',
 'love',
 'her',
 'she',
 'is',
 'nice',
 'to',
 'me',
 ',',
 'by',
 '@',
 'girishchhonkar.com',
 '.']

# StopWords

In [50]:
from nltk.corpus import stopwords

In [62]:
sw = set(stopwords.words('english'))

In [63]:
print(sw)

{'or', "hasn't", 'under', 'theirs', 'does', 'what', 'of', 'any', 'its', 'wouldn', 'by', "mightn't", 'haven', 'other', 'yourselves', 'me', 'shouldn', 'been', "doesn't", 'your', 'mustn', 'the', 'but', 'won', 'am', 'this', 'was', 'above', 'off', 'now', "that'll", 'can', 'that', 'will', 'they', "hadn't", 'same', 'about', 'isn', 'against', 'very', "won't", 'his', 'aren', 'only', "couldn't", 'y', 'didn', 'both', 'with', 'not', 're', 'd', 'weren', 'them', 'her', 'doing', 'more', 's', "shan't", 'be', 'below', 'hers', 'most', 'himself', 'itself', "don't", 'couldn', 'do', 'before', 'yours', 'a', 'where', 'their', 'once', "it's", 'herself', 'whom', "she's", 'why', 'yourself', 'these', 'no', "you'll", 'for', 'having', "shouldn't", "should've", "aren't", 'over', 've', 'because', 'too', 'than', 'she', "you'd", 'at', 'further', 'if', 'needn', 'from', 'he', 'themselves', 'did', 'such', 'here', "needn't", 'hasn', "you're", 'nor', 'our', 'ourselves', 'ma', "wouldn't", 'then', 'just', 'll', 'which', 'som

In [72]:
w = 'I am not bothered by her.'

In [66]:
def remove_stopwords(text,stopwords):
    useful_words = [w for w in text if w not in stopwords]
    return useful_words

In [73]:
remove_stopwords(w.split(),sw)

['I', 'bothered', 'her.']

In [77]:
'am' in sw

True

# Tokenization using Regular Expression

In [82]:
from nltk.tokenize import RegexpTokenizer

In [83]:
sentence = 'Send me all the document at girishchhonkar19@gmail.com.'

In [95]:
tokenizer = RegexpTokenizer('[a-zA-z@]+')

In [96]:
useful_text = tokenizer.tokenize(sentence)

In [97]:
useful_text

['Send',
 'me',
 'all',
 'the',
 'document',
 'at',
 'girishchhonkar',
 '@gmail',
 'com']

# Stemming 
## change the word in its base form

In [98]:
# three type of stemmer snowball, porter, Lancaster stemmer

In [101]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer 

In [102]:
from nltk.stem.lancaster import LancasterStemmer

In [103]:
ps = PorterStemmer()

In [104]:
ps.stem('jumping')

'jump'

In [105]:
ps.stem('jumps')

'jump'

In [106]:
ps.stem('lovely')

'love'

In [107]:
ps.stem('loving')

'love'

In [110]:
ss = SnowballStemmer('english')

In [111]:
ss.stem('loved')

'love'

In [112]:
from nltk.stem import WordNetLemmatizer

In [116]:
wn = WordNetLemmatizer()
wn.lemmatize('jumped')

'jumped'

# Building Vocab and Vectorization

In [118]:
from sklearn.feature_extraction.text import CountVectorizer

In [119]:
cv = CountVectorizer()

In [120]:
corpus = [
    'Indian captain MS Dhoni said in media interaction that he\s confident that his team will win thw world cup',
     'We will win next Lok sabha election says confident Indian PM',
     'The nobel laurate won the heart of people',
     'The movie Raazi is an exciting spy thriller based on real story']

In [121]:
vectorized_corpus = cv.fit_transform(corpus)

In [124]:
vectorized_corpus

<4x43 sparse matrix of type '<class 'numpy.int64'>'
	with 48 stored elements in Compressed Sparse Row format>

In [125]:
vectorized_corpus = vectorized_corpus.toarray()

In [126]:
vectorized_corpus

array([[0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]])

In [127]:
vectorized_corpus[0]

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1])

In [130]:
print(cv.vocabulary_)

{'indian': 12, 'captain': 2, 'ms': 19, 'dhoni': 5, 'said': 29, 'in': 11, 'media': 17, 'interaction': 13, 'that': 34, 'he': 8, 'confident': 3, 'his': 10, 'team': 33, 'will': 39, 'win': 40, 'thw': 37, 'world': 42, 'cup': 4, 'we': 38, 'next': 20, 'lok': 16, 'sabha': 28, 'election': 6, 'says': 30, 'pm': 25, 'the': 35, 'nobel': 21, 'laurate': 15, 'won': 41, 'heart': 9, 'of': 22, 'people': 24, 'movie': 18, 'raazi': 26, 'is': 14, 'an': 0, 'exciting': 7, 'spy': 31, 'thriller': 36, 'based': 1, 'on': 23, 'real': 27, 'story': 32}


In [131]:
numbers = vectorized_corpus[2]

In [132]:
numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0])

In [135]:
s=cv.inverse_transform(vectorized_corpus)

In [136]:
s

[array(['captain', 'confident', 'cup', 'dhoni', 'he', 'his', 'in',
        'indian', 'interaction', 'media', 'ms', 'said', 'team', 'that',
        'thw', 'will', 'win', 'world'], dtype='<U11'),
 array(['confident', 'election', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'we', 'will', 'win'], dtype='<U11'),
 array(['heart', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
       dtype='<U11'),
 array(['an', 'based', 'exciting', 'is', 'movie', 'on', 'raazi', 'real',
        'spy', 'story', 'the', 'thriller'], dtype='<U11')]

# Vectorization with stopword removal

In [173]:
def mytokenizer(document):
    word = tokenizer.tokenize(document.lower())
    
    #remove stopword
    word = remove_stopwords(word,sw)
    return word

In [174]:
sentence = 'send me your document at girishchhonkar19@gmail.com'

In [176]:

#mytokenizer(sentence)

In [177]:
cv=CountVectorizer(tokenizer=mytokenizer)

In [178]:
vector = cv.fit_transform(corpus)

In [179]:
vector = vector.toarray()

In [180]:
len(vector[0])

# earlier this length was 42 but now it is 18 ..so it's a big plus to use stop words removal

32

In [181]:
cv.inverse_transform(vector)

[array(['captain', 'confident', 'cup', 'dhoni', 'he\\s', 'indian',
        'interaction', 'media', 'ms', 'said', 'team', 'thw', 'win',
        'world'], dtype='<U11'),
 array(['confident', 'election', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U11'),
 array(['heart', 'laurate', 'nobel', 'people'], dtype='<U11'),
 array(['based', 'exciting', 'movie', 'raazi', 'real', 'spy', 'story',
        'thriller'], dtype='<U11')]

In [182]:
#For test data , we can't use new stopwords ,we have to use same as train data. 
# so we use transform function only not fit transform.

In [189]:
test_corpus = ['Indian cricket team rocks!']

In [190]:
cv.transform(test_corpus).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [192]:
cv.vocabulary_

{'indian': 9,
 'captain': 1,
 'ms': 15,
 'dhoni': 4,
 'said': 23,
 'media': 13,
 'interaction': 10,
 'he\\s': 7,
 'confident': 2,
 'team': 27,
 'win': 30,
 'thw': 29,
 'world': 31,
 'cup': 3,
 'next': 16,
 'lok': 12,
 'sabha': 22,
 'election': 5,
 'says': 24,
 'pm': 19,
 'nobel': 17,
 'laurate': 11,
 'heart': 8,
 'people': 18,
 'movie': 14,
 'raazi': 20,
 'exciting': 6,
 'spy': 25,
 'thriller': 28,
 'based': 0,
 'real': 21,
 'story': 26}

# More ways to create Feature 
- unigram - every word as a feature
- Bigrams - every two word as feature
- Trigrams
- n-gram
- TF-IDF Normalisation

In [194]:
sent_1 = ['This is a good movie']
sent_2 = ['This is a good movie but actor is not present']
sent_3 = ['This is not a good movie']

In [195]:
cv=CountVectorizer(ngram_range=(1,1))

In [199]:
docs = [sent_1[0],sent_2[0],sent_3[0]]
cv.fit_transform(docs).toarray()

array([[0, 0, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 2, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1]])

In [200]:
cv.vocabulary_

{'this': 7,
 'is': 3,
 'good': 2,
 'movie': 4,
 'but': 1,
 'actor': 0,
 'not': 5,
 'present': 6}

In [201]:
cv= CountVectorizer(ngram_range=(2,2))

In [204]:
cv.fit_transform(docs).toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 1]])

In [203]:
cv.vocabulary_

{'this is': 8,
 'is good': 3,
 'good movie': 2,
 'movie but': 5,
 'but actor': 1,
 'actor is': 0,
 'is not': 4,
 'not present': 7,
 'not good': 6}

In [205]:
cv = CountVectorizer(ngram_range = (1,3))

In [211]:
cv.fit_transform(docs).toarray()

cv.vocabulary_

{'this': 23,
 'is': 9,
 'good': 6,
 'movie': 15,
 'this is': 24,
 'is good': 10,
 'good movie': 7,
 'this is good': 25,
 'is good movie': 11,
 'but': 3,
 'actor': 0,
 'not': 18,
 'present': 22,
 'movie but': 16,
 'but actor': 4,
 'actor is': 1,
 'is not': 12,
 'not present': 21,
 'good movie but': 8,
 'movie but actor': 17,
 'but actor is': 5,
 'actor is not': 2,
 'is not present': 14,
 'not good': 19,
 'this is not': 26,
 'is not good': 13,
 'not good movie': 20}

# Tf-Idf Normalization
- Avoid features that occur very often, because thry contain less information
- Information decrease as the no of occurences increases across different type.
- So we define another term - document -frequency which associates a weight .

In [1]:
sent_1 = "this is a good movie."
sent_2 = "this was a good movie."
sent_3 = "this is not a good movie."

corpus = [sent_1,sent_2,sent_3]

- tf - idf(t,d) = log(N)/(1 + count(t,d))
#where N= total no of document
#how many 't' appeared all docs

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
tfidf = TfidfVectorizer()

In [10]:
vc = tfidf.fit_transform(corpus)

In [11]:
vc.toarray()

array([[0.46333427, 0.59662724, 0.46333427, 0.        , 0.46333427,
        0.        ],
       [0.41285857, 0.        , 0.41285857, 0.        , 0.41285857,
        0.69903033],
       [0.3645444 , 0.46941728, 0.3645444 , 0.61722732, 0.3645444 ,
        0.        ]])

In [12]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}